### ISSUE TITLE
plt_imshow

### ISSUE THREAD

**Issue by rjgtorres** [jacobwilliams/pyplot-fortran#11]
Hello, 

I usually work with 2d data, mostly maps, and I thought you library would be nice to make some quick plots of my data instead of running the fortran code and then jump to python and make the same image.
Problem is my images are very big (3700x3700px) and your method of writing all pixels to the .py make it impossible for me to work.  
I've implemented the method to call the imshow and for images of 1000x1000 it takes around +20s to run and produces a .py of +20MB, so it can be useful to someone if you want to add it to your code.
Anyway, this is a great job and is useful for more simple data.

Best regards,
Ricardo

```fortran
    subroutine add_imshow(me, x)

    class(pyplot),          intent (inout)        :: me           !! pyplot handler
    real(wp),dimension(:,:),intent (in)           :: x            !! x values

    character(len=:), allocatable :: xstr         !! x values stringified
    character(len=*), parameter   :: xname = 'x'  !! x variable name for script

    if (allocated(me%str)) then

        !convert the arrays to strings:
        call matrix_to_string(x, me%real_fmt, xstr, me%use_numpy)

        !write the arrays:
        call me%add_str(trim(xname)//' = '//xstr)
        call me%add_str('')

        !write the plot statement:
        call me%add_str('ax.imshow  ('//&
                        trim(xname)//')')

        call me%add_str('')

    else
        error stop 'Error in add_imshow: pyplot class not properly initialized.'
    end if

    end subroutine add_imshow

```

**Comment by jacobwilliams** [comment]
Sure I can add it. Thanks!

Yep, the simple method I'm using isn't really that optimal for very large data sets. I suppose we could write to a binary file (maybe using h5py) and have the python script read that. That might be quicker and/or produce smaller file sizes. But, I don't know if it's worth it or not.

**Comment by rjgtorres** [comment]
If you want to try to write in hdf5 consider my library: https://github.com/rjgtorres/oo_hdf and then you could call h5py to read.
It is object oriented and really easy to use. 

Nice that you added and "upgraded" the code I sent you, glad to be of use.

Best regards,
Ricardo
