### ISSUE TITLE
Compiling against python directly?

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/pyplot-fortran#13]
Python provides a C API, that lets you call python directly, I was wondering if you ever looked into this rather than using system calls to write out then execute python scripts.

Just starting to get into matplotlib myself, and was wondering if that might be an easier route for the end user... maybe not.

**Comment by jacobwilliams** [comment]
Funny you should mention it...I have started to look into that for a work project. But, I don't know about using it here. Originally I wrote this library just to be super simple way to make some basic plots (it's only one file, has no build dependencies, etc.) Maybe there is some benefit to keeping it simple? Not sure.

**Comment by zbeekman** [comment]
Yes, that's why I was asking... I typically need to make more complex
graphs, so I was contemplating whether or not calling the API directly
would be more appropriate. I'm currently thinking no.... at least until I
have to start doing in situ post processing but I'm probably still a few
years away from exa scale production runs...
