### ISSUE TITLE
Ford API documentation

### ISSUE THREAD

**Issue by szaghi** [jacobwilliams/pyplot-fortran#2]
Hi Jacob,

I am using your great **pyplot-fortran** into WenOOF... it is half an hour and I am already addicted to it... great!

I have a request. Can you transform the docstring into ford-compliant syntax in order to produce well documented API? Or do you accept PR? In case, I can fork pyplot-fortran and submitting PR.

As you can see [here](http://fortran-foss-programmers.github.io/WenOOF/index.html) pytplot-fortran API doc is missing.

**Comment by jacobwilliams** [comment]
Yes, I can do that later today.

**Comment by szaghi** [comment]
Thank you very much!

**Comment by szaghi** [comment]
Thank you very much!
