### ISSUE TITLE
Use OO interface

### ISSUE THREAD

**Issue by hennink** [jacobwilliams/pyplot-fortran#21]
I'd love to use your wonderful project, but unfortunately there is a blocking issue for me.

The current Python code uses matplotlib's GUI, which does not work for me. I have no graphical support, so Python gives me a `RuntimeError: could not open display`. This can easily happen working with remote servers, which I think is common for Fortran programmers.

The solution is to use matplotlib's OO API. So initialize a figure with `matplotlib.figure.Figure`, which, unlike `matplotlib.pyplot.figure`, does not try to open a window. The OO interface is also generally considered better style, and I imagine it might be faster.

This is addressed by pull request #22 .

**Comment by jacobwilliams** [comment]
Thanks! I'll take a look soon.

**Comment by jacobwilliams** [comment]
Merged!

**Comment by hennink** [comment]
Thanks a lot!
