### ISSUE TITLE
Extend matplotlib support

### ISSUE THREAD

**Issue by szaghi** [jacobwilliams/pyplot-fortran#3]
The present status is already useful in many situations, but it would be very appreciated a greater support for most of the matplotlib features.

Have you planned a road-map to extend the library? 

Can I contribute? Do you accept PR? I can fork and try to add other matplotlib interfaces.

**Comment by jacobwilliams** [comment]
Yes, by all means send whatever pull requests you want.

**Comment by szaghi** [comment]
Thank you very much, I will start Monday to try to extend matplotlib support.
