### ISSUE TITLE
Visual Studio 2019

### ISSUE THREAD

**Issue by dwdotson** [jacobwilliams/pyplot-fortran#35]
Jacob, have you tried to compile in Visual Studio 2019? I was wondering if there were any flags that need to be disabled to make it compile. Tried it an had some issues:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Compilation Aborted (code 1)		C:\Users\don.dotson\source\repos\matplotlib\module.f90	1	
Error		error #6251: This symbol has multiple PUBLIC statement/attribute declarations which is not allowed.   [PYPLOT_WP]		C:\Users\don.dotson\source\repos\matplotlib\module.f90	36	
Error		error #6418: This name has already been assigned a data type.   [PYPLOT_WP]		C:\Users\don.dotson\source\repos\matplotlib\module.f90	36	
Error		error #6251: This symbol has multiple PUBLIC statement/attribute declarations which is not allowed.   [PYPLOT_WP]		C:\Users\don.dotson\source\repos\matplotlib\module.f90	38	
Error		error #6251: This symbol has multiple PUBLIC statement/attribute declarations which is not allowed.   [PYPLOT_WP]		C:\Users\don.dotson\source\repos\matplotlib\module.f90	40	
Error		Compilation Aborted (code 1)		C:\Users\don.dotson\source\repos\matplotlib\Source1.f90	1	
Error		error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [PYPLOT_MODULE]		C:\Users\don.dotson\source\repos\matplotlib\Source1.f90	4	
Error		error #6457: This derived type name has not been declared.   [PYPLOT]		C:\Users\don.dotson\source\repos\matplotlib\Source1.f90	9	
Error		error #6404: This name does not have a type, and must have an explicit type.   [PLT]		C:\Users\don.dotson\source\repos\matplotlib\Source1.f90	17	
Error		error #6460: This is not a component name that is defined in the encompassing structure.   [INITIALIZE]		C:\Users\don.dotson\source\repos\matplotlib\Source1.f90	17	
Error		error #6460: This is not a component name that is defined in the encompassing structure.   [ADD_PLOT]		C:\Users\don.dotson\source\repos\matplotlib\Source1.f90	19	
Error		error #6460: This is not a component name that is defined in the encompassing structure.   [SAVEFIG]		C:\Users\don.dotson\source\repos\matplotlib\Source1.f90	20

**Comment by jacobwilliams** [comment]
The file with the `.F90` extension needs to have preprocessing enabled. I don't think VS/Intel does that by default.

**Comment by adityain2003** [comment]
Dear Jacob, 

Can you please guide, how to enable preprocessing in visual studio?

**Comment by jacobwilliams** [comment]
In the VS GUI under the project Property Pages - Configuration properties - Fortran - Preprocess source file.

**Comment by adityain2003** [comment]
Thankyou Jacob, It worked and saved me lots of trouble.
