### ISSUE TITLE
question of debugging

### ISSUE THREAD

**Issue by xiyan12345** [jacobwilliams/pyplot-fortran#48]
thank you for your project!
but I met a question when I was debugging. the result is as follows:
![XX231F~`P6%LI}Q TJ @8RU](https://github.com/jacobwilliams/pyplot-fortran/assets/98223137/e02003a8-061c-480a-8bd3-615b82830c72)

**Comment by jacobwilliams** [comment]
You must have matplotlib installed for this library to work.
