### ISSUE TITLE
Persistent python script file

### ISSUE THREAD

**Issue by szaghi** [jacobwilliams/pyplot-fortran#5]
Hi Jacob,

using your great library I see that the python script used to generate the plots figure (and generated itself from pyplot-fortran) is _persistent_ even if you do not specify a name for it into the _savefig_ method. My expectation was that if I do not specify the name of the python script that file was not persistent, on the contrary if you do not specify the name the script file is simply named with a _temporary_ name.

This is a design feature?

I like to avoid a default _persistent_ script. Maybe a simple solution could to be use the `close(...STATUS='delete)` instead of `close(...)` into the _execute_ method.

**Comment by jacobwilliams** [comment]
I agree. I can make this change. Also, I would like to add a more elegant way to produce a temporary filename, rather than just hard-coding the `tmp_file` string.
