### ISSUE TITLE
Not standard error statement

### ISSUE THREAD

**Issue by szaghi** [jacobwilliams/pyplot-fortran#6]
Hi Jacob,

If I compile pyplot-fortran with a _paranoiac debug mode_ I obtain some warnings like

``` shell
src/tests/pyplot_module.f90(235): warning #6477: Fortran 2008 does not allow this statement or directive.
        error stop 'Error in add_plot: pyplot class not properly initialized.'
-------------------^
```

**Comment by jacobwilliams** [comment]
Are you using ifort? I think this was a bug in earlier versions of the compiler. This statement should be standard conforming.

**Comment by szaghi** [comment]
Yes, this warning should come from ifort 15.x, but I tested also gfortran 5.x thus now I am not sure... tomorrow from office I will be more accurate :-)

**Comment by zbeekman** [comment]
> The statement
> error stop [ stop-code ]
> has been introduced, where stop-code is an integer or default character constant expression.
> When executed on one image, it initiates error termination there and hence causes all other
> images that have not already initiated error termination to initiate error termination. It thus
> causes the whole calculation to stop as soon as is practicable. The meaning of stop-code is
> the same as for the stop statement, see Sections 5.3 and 20.1.6.

From Metcalf, Cohen and Reid

**Comment by szaghi** [comment]
Just checked,

the warnings are printed by Intel 15.0.3 when the compilation flag has `-std08`. This is a minor bug of Intel, because as Zaak pointed out this should be standard (and gfortran 5.2.0 does not complain about it).

Thank you all.
